bug/TD-3284 nowrap typography truncation ellipsis color issue
IPG-Automotive-UK/react-ui pull request #1015
Opened 2024-12-27 10:14 UTC by ShushN

Closes/Contributes [TD-??]()

## Changes

A brief description of what this pull request solves / introduces.

- Some detailed bullet points on what exactly was done.
- ...
- ...

Maybe a short description of what is not included and will come in future work where appropriate.

## Dependencies

## UI/UX

## Testing notes

## Author checklist

Before I request a review:

- [ ] I have reviewed my own code-diff.
- [ ] I have tested the changes in Docker / a deploy-preview.
- [ ] I have assigned the PR to myself or an appropriate delegate.
- [ ] I have added the relevant labels to the PR.
- [ ] I have included appropriate tests.
- [ ] I have checked that the Lint and Test workflows pass on Github.
- [ ] I have populated the deploy-preview with relevant test data.
- [ ] I have tagged a UI/UX designer for review if this PR includes UI/UX changes.

2024-12-27 11:02 UTC, Kaustubh9031 approved these changes
LGTM. Testing can be done after pre-release.

2025-01-02 09:23 UTC, m4manjesh commented
@ShushN Is there a reason you didn't create a release branch for this PR?

2025-01-02 09:24 UTC, Kaustubh9031 commented
> @ShushN Is there a reason you didn't create a release branch for this PR?

2025-01-02 09:26 UTC, Kaustubh9031 commented
@m4manjesh Matt suggested to keep the target branch as `main` as of now.

2025-01-06 13:16 UTC, mattcorner requested changes
The fix made for this PR only resolves the issue when we have links, but we can truncate other text content. The three dots should match the colour of the content which is not always `text.primary`. You fix makes all text content `text.primary` even when it shouldn't be.

See all the examples on main vs this branch:

https://main--666c1309face6e7c27f20e04.chromatic.com/?path=/docs/general-truncatedtooltip--docs

https://666c1309face6e7c27f20e04-bhrkkjsetv.chromatic.com/?path=/docs/general-truncatedtooltip--docs

2025-01-07 04:51 UTC, Kaustubh9031 commented
@mattcorner @ShushN I agree with Matt. When the child component of `NoWrapTypography` has color other than `primary`, it doesn't align with the `primary` color of the overflow `ellipsis`.
A potential solution would be to get the `color` of the `children` in the `NoWrapTypography` and then pass it to the `TruncatedTooltip`. This color then can be used inside `sx` prop in the `TruncatedTooltip`.

**e.g.**
export default function NoWrapTypography({
  children,
  sx,
  variant
}: NoWrapTypographyProps) {
  const color = React.isValidElement(children) && children.props?.sx?.color ? children.props.sx.color : "inherit";
  return (
    <TruncatedTooltip
      component={Typography}
      variant={variant}
      sx={sx}
      color={color}
    >
      {children}
    </TruncatedTooltip>
  );
}

2025-01-08 11:24 UTC, Kaustubh9031 commented on src/TruncatedTooltip/TruncatedTooltip.tsx
> +  console.log(computedColor);
remove console statement

2025-01-08 11:35 UTC, Kaustubh9031 commented on src/TruncatedTooltip/TruncatedTooltip.tsx
> +      // Fetch the computed styles dynamically
The comment does not align with its adjacent line of code. Please write appropriate code comments.

2025-01-08 11:35 UTC, Kaustubh9031 requested changes
Request changes

2025-01-08 15:16 UTC, Kaustubh9031 approved these changes
LGTM. I have tested the changes and it's working as expected.

@mattcorner Please do a final review.

2025-01-08 16:37 UTC, mattcorner requested changes
<img width="235" alt="image" src="https://github.com/user-attachments/assets/f1e0048f-ac3b-4ad0-8ecd-14eef0050660" />

It doesn't work as expected for "Link using children" in dark mode. 

Keep in mind that this component can be rendered with the `component` prop, or the `children`. The issues only seems to occur for the `children` case as per the bug report.

2025-01-08 19:17 UTC, Kaustubh9031 commented
> <img alt="image" width="235" src="https://private-user-images.githubusercontent.com/27866636/401226547-f1e0048f-ac3b-4ad0-8ecd-14eef0050660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNTk4NzQsIm5iZiI6MTczNjM1OTU3NCwicGF0aCI6Ii8yNzg2NjYzNi80MDEyMjY1NDctZjFlMDA0OGYtYWMzYi00YWQwLThlY2QtMTRlZWYwMDUwNjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDE4MDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOTY2NTUyNjU0MDIxMjQwYmQ4MGQ1ZjFjZTY1YmU1ZDYwNDM3YWQ2NzQ1OWYzOGFjZjMyOWM4ZjUzZWZhZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YuSbIEe7EVutGooNCInzMZ0syVOGjEn3PVEitgiJ1xs">
> It doesn't work as expected for "Link using children" in dark mode.
> 
> Keep in mind that this component can be rendered with the `component` prop, or the `children`. The issues only seems to occur for the `children` case as per the bug report.

useEffect(() => {
    if (textElementRef.current?.children.length) {
      // Get the child element of the reference node
      const firstChild = textElementRef.current.children[0] as HTMLElement;
      // Retrieve the computed color style of the child element
      const color = window.getComputedStyle(firstChild).color;
      setComputedColor(color);
    }
  }, [computedColor]);

Changing the dependency array works but need to refresh the page while switching between light and dark mode. Please let know if we can proceed with this.

2025-01-08 19:23 UTC, Kaustubh9031 commented
import { useTheme } from "@mui/material";


const theme = useTheme(); // Access the current theme
  // Ref to the text element.
  const textElementRef = useRef<HTMLInputElement | null>(null);
  const [computedColor, setComputedColor] = useState<string>("");
  useEffect(() => {
    if (textElementRef.current?.children.length) {
      // Get the child element of the reference node
      const firstChild = textElementRef.current.children[0] as HTMLElement;
      // Retrieve the computed color style of the child element
      const color = window.getComputedStyle(firstChild).color;
      setComputedColor(color);
    }
  }, [computedColor, theme]);

Using the useTheme hook from MUI and changing the dependency array to [computedColor, theme] works perfectly.

2025-01-09 16:02 UTC, mattcorner commented
Hey @ShushN @Kaustubh9031. I've had a play around and the underlying `TruncatedTooltip` component itself already does exactly what we need without any changes. It is just being used incorrectly.

I have updated the stories to better reflect how the component should be used. When we want to truncate a link, then we should do something like:

```tsx
<TruncatedTooltip 
    component={Link},
    href: "This/can/take/an/href/prop",
    variant: "body1"
>
   Some long text that will be truncated
<TruncatedTooltip>
```

The reason that this works is the truncation styling gets applied to the component that is passed in as `component`. Hence the ellipsis colour matches the colour of the element being rendered. No client-side JS needed to manipulate the styles.

We then have the problem that we have two incredibly similar components in `NoWrapTypography` and `TruncatedTooltip`.  `NoWrapTypography` was the original component and was never intentionally written to support Links. `TruncatedTooltip` was written to be flexible and was intended to support Links. Unfortunately `NoWrapTypography` is the more widely used component in VIRTO. 

At this point `NoWrapTypography` is a simple wrapper around `TruncatedTooltip` which reduces the functionality and is easily misused as shown in the bug ticket. I suggest we delete the `NoWrapTypography` component from RUI. This would be a breaking change and so I would target suggest targeting RUIv11 alongside the MUIv6 changes.

We would then need to go and replace every usage of `NoWrapTypography` in VIRTO with the correct usage of `TruncatedTooltip`. We would also need to fix any existing [incorrect usage](https://github.com/IPG-Automotive-UK/virto/blob/e994191f147cf9d80a906a5cf529a973da9e89ee/apps/scene/app/src/components/TableView/RenderRoadNameCell.tsx#L15) of the `NoWrapTypography` component.

cc @lukemojo I know you wrote `TruncatedTooltip`. Do you agree with the above proposal?

2025-01-10 10:01 UTC, lukemojo commented
> cc @lukemojo I know you wrote `TruncatedTooltip`. Do you agree with the above proposal?

@mattcorner Apologies for missing this yesterday. Yes I agree with the proposal. The NoWrapTypography component was maintained to prevent a breaking change across Virto but it doesn't make much sense for both components to exist if its causing problems. It will result in slightly more complexity in implementation due to the flexibility. 

Storybook should have all the relevant examples. Note that once you pass the component prop, TruncatedTooltip will then accept all relevant component props. I.e. component={Typography} will allow the component to accept all MUI Typography props. 

The target branch for this will currently be v11 which I will update now.

2025-01-17 05:36 UTC, Kaustubh9031 requested changes
@ShushN Recently some changes have been made as part of MUI v6 migration which is reverted in this PR. Please take care of this and commit again.

2025-01-17 09:31 UTC, Kaustubh9031 commented on src/Filter/CheckboxFilter/CheckboxFilter.tsx
> +      <TruncatedTooltip data-testid="filter-option-label">
pass `typography` as component prop

2025-01-17 09:32 UTC, Kaustubh9031 commented on src/Filter/LabelFilter/LabelFilter.tsx
> +        <TruncatedTooltip>{option.name}</TruncatedTooltip>
pass `typography` as component prop

2025-01-17 09:33 UTC, Kaustubh9031 commented on src/LabelSelector/LabelSelector.jsx
> +                <TruncatedTooltip>{option.name}</TruncatedTooltip>
pass typography as component prop

2025-01-17 10:01 UTC, Kaustubh9031 commented on src/Filter/CheckboxFilter/CheckboxFilter.tsx
> +      <TruncatedTooltip data-testid="filter-option-label">
pass `component={Typography}`

2025-01-17 10:01 UTC, Kaustubh9031 commented on src/Filter/LabelFilter/LabelFilter.tsx
> +        <TruncatedTooltip>{option.name}</TruncatedTooltip>
pass `component={Typography}`

2025-01-17 10:02 UTC, Kaustubh9031 commented on src/LabelSelector/LabelSelector.jsx
> +                <TruncatedTooltip>{option.name}</TruncatedTooltip>
pass `component={Typography}`

2025-01-17 10:02 UTC, Kaustubh9031 commented on src/LabelSelector/LabelSelector.jsx
> +                <TruncatedTooltip variant="caption">
pass `component={Typography}`

2025-01-17 10:06 UTC, Kaustubh9031 commented on src/TruncatedTooltip/TruncatedTooltip.tsx
> +
Remove this extra line

2025-01-17 10:30 UTC, Kaustubh9031 requested changes
Please make the changes based on feedback.

2025-01-20 08:25 UTC, Kaustubh9031 approved these changes
LGTM

2025-01-21 12:30 UTC, merged