TD-518 - Add "Back to App Store" Feature
IPG-Automotive-UK/react-ui pull request #407
Opened 2022-07-01 07:39 UTC by chhack94

This adds a Link element to the IPG Logo in the Top left Corner. The Link gets generated from a environment variable called "REACT_UI_APPSTORE_URL" in each app during the build event, if it is empty the behaviour stays the same as before this feature implementation.

2022-07-01 07:48 UTC, dmbarry86 commented
The implementation here is not quite right. The URL should just be an additional prop on the Sidebar component which gets passed in from each app, not an environment variable. This UI library is completely independent of our app store so should know nothing about it. The prop should just be a generic prop. Each app then manages the actual app store URL during build time using the environment variable and passes it in as the prop value.

2022-07-01 07:49 UTC, dmbarry86 commented on src/Sidebar/Sidebar.js
> +import Link from "@mui/material/Link";
Should be imported on line 1 along with the other material component

2022-07-01 07:49 UTC, dmbarry86 commented
Please add a new test for this new behaviour. I would expect two tests. The first that no link is shown when the prop is empty. The 2nd that the link is shown when prop is set and has correct URL.

2022-07-01 07:50 UTC, dmbarry86 requested changes
Few things to update.

2022-07-01 09:27 UTC, dmbarry86 commented
> Storybook would also need updating to include the new prop and add a new story for the link behaviour.

Don't forget this.

2022-07-01 09:29 UTC, dmbarry86 requested changes
Add new story to storybook for Sidebar component.

2022-07-01 09:30 UTC, chhack94 commented
> > Storybook would also need updating to include the new prop and add a new story for the link behaviour.
> 
> Don't forget this.

my bad, sorry

2022-07-01 10:41 UTC, dmbarry86 commented
New story is good but all of the other stories against sidebar now also have a link which when clicked takes to a page with just the sidebar which isn't quite right. I think all other stories shouldn't be showing link at all. Looks like there is a # in there somewhere causing the issue. I think default should just be empty.

2022-07-01 10:43 UTC, dmbarry86 requested changes
Link is still being shown even when logoLinkUrl prop is not set.

2022-07-04 07:17 UTC, dmbarry86 approved these changes

2022-07-04 07:17 UTC, merged