Feature/app header
IPG-Automotive-UK/react-ui pull request #525
Opened 2023-02-28 12:29 UTC by m4manjesh

Closes https://sce.myjetbrains.com/youtrack/issue/TD-1379/Create-new-react-ui-component-for-header

2023-02-28 16:18 UTC, m4manjesh commented
> @m4manjesh can you link the latest figma prototype. I had a look for one, but it doesn't look like what you've implemented so I assume there is a newer version.

Added in the description.

2023-02-28 16:44 UTC, dmbarry86 commented
@m4manjesh have you tried integrating this with an app yet to check it looks and works as expected? If not, please do a pre-release build now and test it out so we can confirm all is ok. Send me a link to an app that conmtians it when done.

2023-02-28 16:48 UTC, dmbarry86 commented
Why is there a sidebar shown in the app header story? Is the sidebar actually part of the component? I don't think it should be.

![image](https://user-images.githubusercontent.com/8976377/221921054-d402930f-db36-44a2-9d82-bb83f47dfb24.png)

2023-02-28 16:50 UTC, dmbarry86 commented
The APP NAME text is not aligned with VIRTO text. Also looks slightly different font or size.

Figma:
![image](https://user-images.githubusercontent.com/8976377/221921523-76c4a187-be2e-412b-b481-c55e5c3750f8.png)


This branch:
![image](https://user-images.githubusercontent.com/8976377/221921483-e260aa06-dfc6-412e-a0cc-86b632f29cf2.png)

2023-02-28 16:55 UTC, dmbarry86 commented
Prop names should be camelCase. Both logo link props are wrong. I also don't think you need a prop for IPG link. That should just be fixed to IPG website https://ipg-automotive.com/

![image](https://user-images.githubusercontent.com/8976377/221922731-cfeb1ae7-5fcd-4bc0-8a29-bec80c4319d7.png)

2023-02-28 16:56 UTC, dmbarry86 commented
Which is mode a prop? Surely this is internal to the component and is set by the dark/light toggle switch that is part of the component. What else would be setting this in an app?

![image](https://user-images.githubusercontent.com/8976377/221923162-0017197e-8b01-41ec-a076-916c6a7ff23a.png)

2023-02-28 16:58 UTC, dmbarry86 commented
Why do we need these props to show/hide these items? When would we ever hide them? Is there a particular app that needs them hidden?

![image](https://user-images.githubusercontent.com/8976377/221923549-51779151-5771-4f4f-b705-04222263b1f9.png)

2023-02-28 17:01 UTC, dmbarry86 commented
Is this the intended design for disabled buttons in dark mode to have the light grey transparent background? I don't see anything in Figma with disabled buttons so just checking. @Sowbhagya-ipg to confirm.

![image](https://user-images.githubusercontent.com/8976377/221924344-198ccf6c-120d-4770-9a36-0367a27198e7.png)

2023-02-28 17:03 UTC, dmbarry86 commented
The icons are smaller compared to Figma.

Figma (67px):
![Screenshot 2023-02-28 at 17 01 44](https://user-images.githubusercontent.com/8976377/221924616-753d76b9-e838-45ac-9da3-cba84a693eda.png)

This branch (54.32px):
![image](https://user-images.githubusercontent.com/8976377/221924799-cfde4589-202d-4517-ad59-2915a8fb3e8d.png)

2023-02-28 17:06 UTC, dmbarry86 commented
The app bar background color does not match Figma. Also note that the app text is black and doesn't match the color of the VIRTO text.

Figma:
![image](https://user-images.githubusercontent.com/8976377/221925628-dacdecfc-e113-4545-99dc-68195015fe34.png)

This branch:
![image](https://user-images.githubusercontent.com/8976377/221925715-c6c79ead-e9f4-44c7-ae4e-0e2912767704.png)

2023-02-28 17:10 UTC, dmbarry86 commented
Is this the expected design to show two menu buttons when the sidebar is collapsed? This doesn't feel nice to me. I don't see anything in Figma for this. @Sowbhagya-ipg to confirm expected behaviour here. Maybe we don't need to collapse sidebar anymore?

![image](https://user-images.githubusercontent.com/8976377/221926568-3f951e7d-c04f-463f-b685-3f4a0004b38b.png)

2023-02-28 17:13 UTC, dmbarry86 commented
Figma shows hover effect on each app button but this branch doesn't.

Figma:
https://user-images.githubusercontent.com/8976377/221927024-07f9a5ad-5a54-4ea7-8115-4420cf8f4352.mov

This branch:
https://user-images.githubusercontent.com/8976377/221927153-6828ed9a-ea68-4659-bbee-24f51cfa6bbc.mov

2023-02-28 17:18 UTC, dmbarry86 commented on src/AppHeader/AppHeader.test.js
> +  test("should render app name", () => {
The tests for the app header component are somewhat lacking in coverage...

We can do better here. Please create a separate task to improve this after the code freeze.

2023-02-28 17:20 UTC, dmbarry86 requested changes
A few items to address. If you are planning to handle some of them as separate PRs then please leave comment against my respective comment so we keep track.

2023-02-28 17:53 UTC, dmbarry86 commented
> Why is there a sidebar shown in the app header story? Is the sidebar actually part of the component? I don't think it should be

We just had a call to discuss this. Agreed that it's useful to have a top level wrapper component that can render header, sidebar and content. However, that component is not AppHeader. We agreed to rename this component to AppLayout or such like and then have props for sidebarItems and content. At the moment, the current implementation doesn't allow any actual app content to be rendered. This AppLayout component can then contain all of the code we currently have in Layout of each app, including the ThemeProvider wrapping.

2023-03-01 08:23 UTC, Sowbhagya-ipg commented
> Is this the expected design to show two menu buttons on the left when the sidebar is collapsed? This doesn't feel nice to me. I don't see anything in Figma for this. @Sowbhagya-ipg to confirm expected behaviour here. Maybe we don't need to collapse sidebar anymore?
> 
> ![image](https://user-images.githubusercontent.com/8976377/221926568-3f951e7d-c04f-463f-b685-3f4a0004b38b.png)

We need the collapse Menu. Here, the position of icons has to be changed. More apps menu icon (9 dots) on the left most. @m4manjesh @dmbarry86

2023-03-01 08:31 UTC, Sowbhagya-ipg commented
> Is this the intended design for disabled buttons in dark mode to have the light grey transparent background? I don't see anything in Figma with disabled buttons so just checking. @Sowbhagya-ipg to confirm.
> 
> ![image](https://user-images.githubusercontent.com/8976377/221924344-198ccf6c-120d-4770-9a36-0367a27198e7.png)

This is fine.

2023-03-01 09:35 UTC, m4manjesh commented
> @m4manjesh have you tried integrating this with an app yet to check it looks and works as expected? If not, please do a pre-release build now and test it out so we can confirm all is ok. Send me a link to an app branch that contains it when done and I will use that as part of the review.

I have done a pre-release and tested it in MM with some default data. This is the branch, please take a look https://github.com/IPG-Automotive-UK/model-manager/tree/feature/layout-update

2023-03-01 09:36 UTC, m4manjesh commented
> The APP NAME text is not vertically aligned with VIRTO text. Also looks slightly different font or size.
> 
> Figma: ![image](https://user-images.githubusercontent.com/8976377/221921523-76c4a187-be2e-412b-b481-c55e5c3750f8.png)
> 
> This branch: ![image](https://user-images.githubusercontent.com/8976377/221921782-5aa4062a-1009-41fc-990b-ed19950c1bc2.png)

Done and can test in MM branch.

2023-03-01 09:37 UTC, m4manjesh commented
> User menu does not align with Figma. Neither does the dark/light switch.
> 
> Figma: ![image](https://user-images.githubusercontent.com/8976377/221922016-a0bb930f-93e1-445e-8552-b99c45a7619d.png)
> 
> This branch: ![image](https://user-images.githubusercontent.com/8976377/221921984-1a221926-578e-4e39-bad9-deb4a0336bc0.png)

@nikitharani is working on this. https://github.com/IPG-Automotive-UK/react-ui/pull/526

2023-03-01 09:38 UTC, m4manjesh commented
> Done and can test in MM branch.

Done and can test in MM branch.

2023-03-01 09:39 UTC, m4manjesh commented
> Why do we need these props to show/hide these items? When would we ever hide them? Is there a particular app that needs them hidden?
> 
> ![image](https://user-images.githubusercontent.com/8976377/221923549-51779151-5771-4f4f-b705-04222263b1f9.png)

No, removed as discussed. Can test in MM branch.

2023-03-01 10:25 UTC, m4manjesh commented
@dmbarry86  I am done with the changes. Had a chat with @Sowbhagya-ipg about the AppLauncher dark mode hover effect, she is fine with the new hover styles I have added.

2023-03-01 11:30 UTC, dmbarry86 requested changes
Almost there. Few small styling issues as mentioned in chat.

- [x] Spacing between top of sidebar item and the app bar.
- [x] APP NAME text height/position not aligned with VIRTO image.
- [ ] Small jumping in app bar height as I resize window. May just be Storybook issue in which case not too much of a problem but just double check in an app itself.

2023-03-01 13:14 UTC, m4manjesh commented
> Almost there. Few small styling issues as mentioned in chat.
> 
> * [x]  Spacing between top of sidebar item and the app bar.
> * [x]  APP NAME text height/position not aligned with VIRTO image.
> * [x]  Small jumping in app bar height as I resize window. May just be Storybook issue in which case not too much of a problem but just double check in an app itself.

As mentioned in the chat the jumping is only in storybook. The updated layout in MM can find here, please take a look.
https://github.com/IPG-Automotive-UK/model-manager/tree/feature/layout-update

2023-03-01 14:24 UTC, merged