Migrating components to ts
IPG-Automotive-UK/react-ui pull request #579
Opened 2023-04-25 07:23 UTC by nikitharani

Contributes to [TD-1667](https://sce.myjetbrains.com/youtrack/issue/TD-1667/Fix-Images-for-MM-in-Dark-and-Light-mode)

## Changes

- Migrated AppLayout, AppLauncher, AppHeader, Sidebar, user menu, and NowrapTypography Component to TS
- imported and added the ConfirmProvider component in AppLayout to avoid importing ConfirmProvider in individual apps.
- removed divider from SummaryCard

Maybe a short description of what is not included and will come in future work where appropriate.

- Haven't migrated SummaryCard to Ts this will be done in future sprints.

## Testing notes
- You should run the npm test to confirm that the tests work. 

- You should run npm run build and check that the dist/ folder contains .d.ts files containing the type definitions

## Author checklist before assigning a reviewer

- [ ] Reviewed my own code-diff.
- [ ] Assigned to me.
- [ ] Relevant tags added.
- [ ] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

2023-04-25 11:43 UTC, mattcorner commented
@nikitharani You've made UI changes here, but not included any UI screenshots in the PR description for @Sowbhagya-ipg to review. Please make sure you do this.

@Sowbhagya-ipg Here is the change that removes the divider in the SummaryCard. Does this match your expectation?

![image](https://user-images.githubusercontent.com/27866636/234266267-45c54b21-c8e2-4e9e-9996-89043b70f1fc.png)

2023-04-25 11:44 UTC, mattcorner requested changes
Some typescript based stuff to fix.

2023-04-25 11:44 UTC, mattcorner commented on src/AppHeader/AppHeader.types.ts
> +   * A String of the href URL for the Link of the VIRTO Logo, default is null (link disabled)
You've changed this to not use null for some reason, but haven't updated the doc. Be consistent.

2023-04-25 11:44 UTC, mattcorner commented on src/UserMenu/UserMenu.types.ts
> +   * ```
![image](https://user-images.githubusercontent.com/27866636/234265505-a0381b04-f877-4854-a423-577887a2b59c.png)

As shown here, the typescript signature is added below our documentation.

2023-04-25 11:50 UTC, Sowbhagya-ipg commented
> @nikitharani You've made UI changes here, but not included any UI screenshots in the PR description for @Sowbhagya-ipg to review. Please make sure you do this.
> 
> @Sowbhagya-ipg Here is the change that removes the divider in the SummaryCard. Does this match your expectation?
> 
> ![image](https://user-images.githubusercontent.com/27866636/234266267-45c54b21-c8e2-4e9e-9996-89043b70f1fc.png)

1. @mattcorner @nikitharani View all button is not needed at all.
2. The Left side text should be of secondary color
3. Removing the divider is alright here, But the extra empty space is not needed. The height should adjust based on the content

2023-04-25 15:14 UTC, Sowbhagya-ipg commented
> > > 
> > 
> > 
> > > > > @nikitharani You've made UI changes here, but not included any UI screenshots in the PR description for @Sowbhagya-ipg to review. Please make sure you do this.
> > > > > @Sowbhagya-ipg Here is the change that removes the divider in the SummaryCard. Does this match your expectation?
> > > > > ![image](https://user-images.githubusercontent.com/27866636/234266267-45c54b21-c8e2-4e9e-9996-89043b70f1fc.png)
> > > > 
> > > > 
> > > > 
> > > > 1. @mattcorner @nikitharani View all button is not needed at all.
> > > > 2. The Left side text should be of secondary color
> > > > 3. Removing the divider is alright here, But the extra empty space is not needed. The height should adjust based on the content
> > > 
> > > 
> > > 
> > > 1. Is just an example of usage. We can update the story if you don't ever see a use case for >1 button.
> > > 2. The extra space is a valid use case I believe. e.g. in VIRTO.MODEL different summary cards show different numbers of metadata according to Figma.
> > 
> > 
> > The extra space will be adjusted in apps by adding/adjusting the height of the card based on the number of metadata. Here I can adjust height inside the story to match with Figma
> 
> Updated CardComponent ![image](https://user-images.githubusercontent.com/49191249/234302160-4da2955a-abf6-4574-93d0-439f652871a9.png)

This is good.

2023-04-25 21:14 UTC, mattcorner requested changes

2023-04-25 21:14 UTC, mattcorner commented on src/Card/SummaryCard/SummaryCard.stories.js
> +// import { NoWrapTypography } from "../../NoWrapTypography";
Remove this line.

2023-04-26 07:47 UTC, nikitharani commented on src/Sidebar/SidebarItem/SidebarItem.types.ts
> +  iconStyle?: Object;
added CssProperties in commit [f6ef24c](https://github.com/IPG-Automotive-UK/react-ui/pull/579/commits/f6ef24cd2b3256e70f2d48e77d0191c8ea0dc852)

2023-04-26 10:28 UTC, nikitharani commented on src/Sidebar/SidebarItem/SidebarItem.types.ts
> +  iconStyle?: Object;
ignore the previous comment resolved now.

2023-04-26 11:10 UTC, mattcorner approved these changes

2023-04-26 13:44 UTC, merged