Feature/new app layout
IPG-Automotive-UK/react-ui pull request #604
Opened 2023-05-11 17:03 UTC by jegasriskantha

relates to relates to https://github.com/IPG-Automotive-UK/cloud-licensing-web/issues/274

## Changes

- Adds a new generic layout that will be used in the cloud licensing app

- The generic layout builds on the VIRTO app layout but uses the newly created generic app header and has a sidebar width that is designed to be used with the the stacked variant of the sidebar item. 

- When trying to configure the app layout for the cloud licensing app I noticed an issue with the sidebarItem types and some padding when the sidebarItems are stacked, I have made updates to both these here. 
  - iconStyle and TextStyle now have the SxProps type not the CSSProperties type. This is more appropriate and allows for things like this `  textStyle={{ ".MuiTypography-root": { fontSize: "12px" } }}` which CSSProperties does not. 
  - I removed the left and right padding on the ListItemButton when the items are "stacked" to align with the styling in the Figma prototype for Cloud Licensing. 

### Do Not Merge
This PR builds of work done here: https://github.com/IPG-Automotive-UK/react-ui/pull/602 and should not be merged till this is merged.

## UI/UX
This is the default app layout
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/75164177/422cdf87-3663-4a26-a75b-b0bf9553a4a6)

This is what the app layout looks like configured for cloud licensing as per the figma prototype
@Sowbhagya-ipg does this look alright? 
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/75164177/256e3d16-31ff-4505-9265-d21b9195ab87)

This is the Figma prototype:
https://www.figma.com/proto/O3IAobLTPcjIO1WaxaPod6/IPG-Cloud-Licensing?node-id=68-14265&starting-point-node-id=68%3A14265
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/75164177/d068c94a-c841-4346-8d3a-6f442030a243)

## Author checklist before assigning a reviewer

- [ ] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [ ] Assigned to me.
- [ ] Relevant tags added.
- [ ] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

2023-05-12 08:17 UTC, Sowbhagya-ipg commented
The app bar margin on the left and right doesn't seem equal. @jegasriskantha  Please check.

2023-05-12 10:03 UTC, Sowbhagya-ipg commented
Checked with @jegasriskantha. Look's Good

2023-05-12 15:34 UTC, jegasriskantha commented
Apologies @nikitharani  I had missed some exports, they have been updated now.

2023-05-16 08:45 UTC, nikitharani requested changes
Just a small change requested otherwise LGTM.

2023-05-16 08:45 UTC, nikitharani commented on src/AppLayout/AppLayout.types.ts
> +   * **Signature**
we can remove signatures

2023-05-20 15:32 UTC, merged