TD-1810
IPG-Automotive-UK/react-ui pull request #635
Opened 2023-06-13 11:31 UTC by m4manjesh

Closes [TD-1810](https://sce.myjetbrains.com/youtrack/issue/TD-1810/Detail-card-sub-text-color-change)

## Changes

- Updated `DetailCard` component "Updated..." text color to match Figma.
- Convert `DetailCard, FileCard` and `SearchBar` components to typescript.
- Created a `Common.types.ts` file to keep common types
- Increased the title font weight to match Figma

## UI/UX

@Sowbhagya-ipg Please take a look.

On Devel
![MicrosoftTeams-image (11) (1)](https://github.com/IPG-Automotive-UK/react-ui/assets/56511816/2acd7ef5-f5a2-49d7-9816-20944a250cdb)

On this branch
![screenshot-localhost_6006-2023 06 14-09_11_34](https://github.com/IPG-Automotive-UK/react-ui/assets/56511816/42156e4a-fb7a-4108-898b-e3f0872b6e13)

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [x] Lint and test workflows pass.

2023-06-13 14:43 UTC, nikitharani requested changes
I have reviewed and I think you missed a few bits to migrate to ts
- [x] Resolve Comments
- [x] stories.tsx files are not completely migrated to ts you just renamed them to tsx. Please look into components that are already ts for example
- [x] FileCard tests are also not migrated to ts
- [ ] index files should be converted to ts and don't forget to export types.

2023-06-13 14:56 UTC, m4manjesh commented on src/Card/DetailCard/DetailCard.types.ts
> +  labels?: Array<{
It is already using types of Label

2023-06-13 14:57 UTC, m4manjesh commented on src/Card/DetailCard/DetailCard.types.ts
> +  onClickLabel?: (label: {
It is already using types of Label

2023-06-13 14:58 UTC, m4manjesh commented on src/Card/DetailCard/DetailCard.types.ts
> +  labels?: Array<{
Is it duplicated comment?

2023-06-14 09:53 UTC, nikitharani requested changes
Just a small thing please remove the commented code I think you missed to remove. Also, add the Figma link in the PR description next time. Other than this everything LGTM.

2023-06-14 09:53 UTC, nikitharani commented on src/Card/DetailCard/DetailCard.tsx
>      // setButtonStackWidth(buttonStackRef.current.clientWidth);
this is not resolved yet

2023-06-14 11:24 UTC, nikitharani approved these changes
LGTM. I'll leave you to merge and release.

2023-06-14 11:48 UTC, merged