TD 2069 vehicle select dialog
IPG-Automotive-UK/react-ui pull request #695
Opened 2023-08-29 08:00 UTC by nikitharani

Closes [TD-2069](https://sce.myjetbrains.com/youtrack/issue/TD-2069/Create-add-vehicle-dialog)
Figma: https://www.figma.com/proto/B75H0DFTEiUFjJtehIKa8M/VIRTO.MODEL?node-id=522-57017&scaling=scale-down&page-id=0%3A1&starting-point-node-id=228%3A28915

## Changes
- Created a new VehicleSelectDialog component
- Enables the "Add Vehicle" upon valid vehicle selection
- Added callback to return the currently selected vehicles
- Upgraded to node version 18 and upgraded the actions/setup-node action to the latest version
- Moved ActionDialog, DialogTitle, and VehicleSelectDialog components under the Dialog category from General
- Renamed selected vehicles to value, all gates to gates, on vehicle change to onChange, allVehicles to variants to be consistent with vehicleSelect Component
- Added a new prop disableCloseOnSelect to the AutoComplete Component
- Enabled disableCloseOnSelect on multi-select Autocompletes inside VehicleSelect Component
- Because of the disableCloseOnSelect prop which prevents the dropdown from closing when an option is selected (VehicleSlect Component test failed). Modified tests to explicitly close the dropdown after selecting an option using userEvent.click.

## UI/UX
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/49191249/519d0863-f342-4bc4-a83d-a91bba10d78f)

Enables the "Add Vehicle" upon valid vehicle selection
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/49191249/d6ab5e41-d5ea-4703-b94f-0f08e76a05e2)

 The callback returns the currently selected vehicles
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/49191249/0d74e9c5-3726-44a6-b1a5-09e036640559)

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [x] Lint and test workflows pass.

2023-08-29 11:34 UTC, evoinea commented
@Sowbhagya-ipg can you please have a look on UI/UX changes?

2023-08-29 11:35 UTC, Sowbhagya-ipg commented
> @Sowbhagya-ipg can you please have a look on UI/UX changes?

thanks for tagging me. I will do it now

2023-08-29 14:06 UTC, evoinea requested changes
Few small changes required.

2023-08-29 14:06 UTC, evoinea commented on src/VehicleSelectDialog/VehicleSelectDialog.test.tsx
> +  const modifiedVehicles = [...selectedVehicles];
```suggestion
  const modifiedVehicles = [...selectedVehicles];
  
```

2023-08-29 14:06 UTC, evoinea commented on src/VehicleSelectDialog/VehicleSelectDialog.test.tsx
> +
Please add missing comment

2023-08-29 14:06 UTC, evoinea commented on src/VehicleSelectDialog/VehicleSelectDialog.stories.tsx
> +
Missing comments

2023-08-29 14:06 UTC, evoinea commented on src/VehicleSelectDialog/VehicleSelectDialog.stories.tsx
> +
Missing block comment

2023-08-30 08:43 UTC, evoinea commented
I've deleted the Model Year, but this didn't clear the vehicle variant and the gate; it just disabled them:
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/89025096/048039cd-d9cd-493a-a294-cd77447c11de)

2023-08-30 13:16 UTC, dmbarry86 commented
I think the interface for this component has been designed wrong and makes it harded to use than it should be. The dialog itself should be handling the local state when user selects items. You don't need to expose onChange callback from the dialog and manage state outside of the component and then pass in value. You only need onCancelClick and onSaveClick callbacks in this component. Component itself listens to onChange in the VehicleSelect and keeps state in synch then when onSaveClick is called you just need to pass out what the currently selected value is. Otherwise everywhere that uses this component then needs to handle onChange and have external value state. I don't think we ever need to open the dialog with initial values selected so I don't think we need values and onChange props. It's a much simpler interface without them.

2023-08-30 15:22 UTC, dmbarry86 commented
these props are still showing for me in Storybook

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/8976377/8d110eb5-2bdb-4644-87a0-5c0d76e76e2e)

2023-08-30 15:24 UTC, dmbarry86 commented
the props are also still included in the type definition

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/8976377/f02f7ff2-6b82-47c6-b1a4-0e8383032b32)

2023-08-30 15:27 UTC, dmbarry86 requested changes
- [ ] remove onChange and value from storybook
- [ ] remove onChange and value from types
- [ ] ensure state is reset when dialog is opened

2023-08-30 16:36 UTC, dmbarry86 approved these changes

2023-08-30 16:51 UTC, merged