Add all type definitions & fix typescript issues
IPG-Automotive-UK/react-ui pull request #726
Opened 2023-09-19 09:00 UTC by dmbarry86

Closes TD-??
Contributes to TD-???

## Changes

A brief description of what this pull request solves / introduces.

- Some detailed bullet points on what exactly was done.
- ...
- ...

Maybe a short description of what is not included and will come in future work where appropriate.

## Dependencies

## UI/UX

## Testing notes

## Author checklist before assigning a reviewer

- [ ] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [ ] PR assigned to me or an appropriate delegate.
- [ ] Relevant labels added to the PR.
- [ ] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

2023-09-19 15:04 UTC, mattcorner requested changes

2023-09-19 15:33 UTC, dmbarry86 commented on src/NoWrapTypography/NoWrapTypography.tsx
> -          ...(Array.isArray(sx) ? sx : [sx])
Yes TS was whinging. I don't think we support sx as an array so the direct spreading should be ok?

2023-09-19 15:34 UTC, dmbarry86 commented on src/LabelSelector/Label.types.ts
> +  _id: string;
I think we actually have an inconsistency here between the various label components. I thought I had addressed them all to align with _id which I guess is what we actually pass in reality straight from the database. I'll go back through and check.

2023-09-19 15:52 UTC, dmbarry86 commented on src/LabelSelector/Label.types.ts
> +  _id: string;
Check results:
* Filter / LabelFilter - Is documented as _id and correctly using _id ✅
* LabelSelector / DeleteLabelDialog - Was documented as id but never actually using it anywhere. I have updated to use _id. ❌
* LabelSelector / EditLabelDialog - Was documented as both _id and id but was using id. I have aligned to use _id. ❌
* LabelSelector - Was documented as _id but implementation was using both _id and id. I have aligned to use _id. ❌
* MultiLabelPopover  - Is documented as _id and correctly using _id ✅

2023-09-20 09:15 UTC, mattcorner approved these changes

2023-09-20 09:57 UTC, merged