LoadErrorMessage component
IPG-Automotive-UK/react-ui pull request #760
Opened 2023-10-23 15:00 UTC by syedsalehinipg

Contributes to [TD-2030](https://sce.myjetbrains.com/youtrack/issue/TD-2030)

## Changes

- Implemented a flexible and customizable error message component named LoadErrorMessage.
- Incorporated a toggleable "View More Details" section to reveal additional error information when provided.
- Integrated an optional action button that executes a specified callback function when clicked.
- Added a "Contact Team" section with an optional support URL that opens in a new tab when clicked.

## Dependencies

## UI/UX

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/143519265/42d226f4-ff38-4974-b944-581d1904301c)

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/143519265/3d4b8b37-da3e-4d9a-bb03-b60a0a7aad33)

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/143519265/60e4de36-307c-4182-b2b8-2f43f54af831)

## Testing notes

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

2023-10-24 08:07 UTC, m4manjesh commented
@syedsalehinipg is there any Figma?

2023-10-24 08:20 UTC, syedsalehinipg commented
> @syedsalehinipg is there any Figma?

Yes, please find the URL from in the description.

2023-10-24 11:06 UTC, Sowbhagya-ipg commented
@syedsalehinipg  We need to work on the dark theme for these Components. I will quickly update the mockup for you to work on it.

2023-10-24 12:52 UTC, m4manjesh requested changes
Some code changes required and a question. See comments.

2023-10-24 16:02 UTC, syedsalehinipg commented on src/LoadErrorMessage/LoadErrorMessage.tsx
> +            display="flex"
I am not sure if the Snackbar is the right one for this but I have used the Alert instead

2023-10-24 16:06 UTC, syedsalehinipg commented on src/LoadErrorMessage/LoadErrorMessage.spec.tsx
> +test("Renders the title", async ({ page }) => {
That was my understanding, @VictorCLLucas can you please confirm?

2023-10-25 15:01 UTC, m4manjesh commented on src/LoadErrorMessage/LoadErrorMessage.spec.tsx
> +test("Renders the title", async ({ page }) => {
We should always go with a better and easy to use one, so here i am okay with Playwright.

2023-10-26 08:31 UTC, m4manjesh approved these changes
LGTM

2023-10-26 09:22 UTC, merged