TreeViewList Component
IPG-Automotive-UK/react-ui pull request #806
Opened 2024-01-17 14:01 UTC by syedsalehinipg

Contributes to [TD-2030](https://sce.myjetbrains.com/youtrack/issue/TD-2030) Migrating VIRTO.DATA to Remix

## Changes

The PR introduces a new TreeViewList component that renders a tree view list. This component can be used to display hierarchical data in a tree structure.

- The TreeViewList component accepts several props including items, selected, searchTerm, defaultExpanded, and onSelectionChange. These props allow for customization of the tree view list.
- The TreeViewList component supports tooltips. When a tree item is hovered over, a tooltip with the item's name and additional information is displayed.
- The TreeViewList component includes a search function that can filter the items in the tree view list based on a search term.

## UI/UX

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/143519265/56c1cd2a-0580-43cc-88ec-0f104cf3dbac)

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/143519265/9a1542a8-c538-4ef4-b72c-ed334aa13b9a)

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/143519265/ae932c14-0ccc-47e9-b27a-4d335249ac70)

## Testing notes

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [x] Lint and test workflows pass.

2024-01-18 09:25 UTC, mattcorner commented
We also have a TreeView in VIRTO.BUILD. Can we check that this react-ui component incorporates all of the uses cases from BUILD as well so that we can switch to this common component in the future. @evoinea any unique use cases that you are aware of?

<img width="423" alt="image" src="https://github.com/IPG-Automotive-UK/react-ui/assets/27866636/e9e9f1ed-12be-476d-9bc4-d04d32c1f5a5">

2024-01-18 23:06 UTC, m4manjesh commented
@syedsalehinipg  Did a bash test and the UI looks good and works fine. As I am away for a couple of days if you are adding more details based on the above comment made by Matt into this PR please ask someone to do the final review.

2024-01-23 12:34 UTC, evoinea requested changes
Looks good. Minor formatting suggestions to address.

2024-01-23 12:34 UTC, evoinea commented on src/TreeViewList/TreeViewList.tsx
> +  // Iterate through each item
```suggestion
  // iterate through each item
```

2024-01-23 12:34 UTC, evoinea commented on src/TreeViewList/TreeViewList.tsx
> +    if (Array.isArray(item.options)) {
```suggestion
// parse options and children recursively
    if (Array.isArray(item.options)) {
```

2024-01-23 12:34 UTC, evoinea commented on src/TreeViewList/TreeViewList.tsx
> +  // Recursive search function
```suggestion
  // recursive search function
```

2024-01-23 12:34 UTC, evoinea commented on src/TreeViewList/TreeViewList.tsx
> +        // If the item matches any of the search terms, return the whole item
```suggestion
        // if the item matches any of the search terms, return the whole item
```

2024-01-23 12:44 UTC, evoinea commented
Have you demoed this new component to @Sowbhagya-ipg?

2024-01-23 15:53 UTC, evoinea approved these changes
LGTM

2024-01-23 16:14 UTC, merged