TD 2658 Expose Ref for Wizard Content
IPG-Automotive-UK/react-ui pull request #857
Opened 2024-05-02 18:29 UTC by jegasriskantha

Contributes to [TD-2658](https://sce.myjetbrains.com/youtrack/issue/TD-2658/Create-Step-3)

## Changes

Updates the WizardContent to pass on a ref to the underlying box component. This is done so that the scroll postion of the scroll bar in the WizardContent can be set. 

## Dependencies

N/A

## UI/UX

N/A

## Testing notes

- Not much to test here, just check that the ref forwarding looks correct. 

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

2024-05-02 18:49 UTC, jegasriskantha commented
Tests are failing due to flaky playwright tests

2024-05-03 18:05 UTC, syedsalehinipg commented on src/Wizard/WizardContent/WizardContent.tsx
> +export default React.forwardRef(function WizardContent(
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/143519265/85f5f158-b485-4686-b8c3-2a8b32479438)


I think we should add type for ref for type safety
```suggestion
export default React.forwardRef<HTMLDivElement>(function WizardContent(
```

2024-05-03 18:07 UTC, syedsalehinipg requested changes
There seems to be a conflict with the `package-lock.json` if you can fix that please,

2024-05-07 10:28 UTC, syedsalehinipg commented on src/Wizard/WizardContent/WizardContent.tsx
> +) {
I seem to get an eslint error:

![image](https://github.com/IPG-Automotive-UK/react-ui/assets/143519265/28b857d7-da3f-4ed7-b970-1069d7482d02)

The suggestion fixes it:

```suggestion
export default React.forwardRef<HTMLDivElement, WizardContentProps>(
  function WizardContent({ children }, ref) {
```

2024-05-07 13:33 UTC, syedsalehinipg approved these changes

2024-05-16 11:06 UTC, closed without merging