Bug - TD-2849 Fix Breadcrumb truncation defect
IPG-Automotive-UK/react-ui pull request #899
Opened 2024-06-28 10:38 UTC by lukemojo

Closes TD-2849

## Changes

Changes breadcrumbs so only the final item is truncated and wrapped in a tooltip 

- Update component to only use the truncated tooltip on the final item
- Update styles to prevent all other items from shrinking

## UI/UX
<img width="424" alt="Screenshot 2024-06-28 at 11 37 17" src="https://github.com/IPG-Automotive-UK/react-ui/assets/143453762/4bb47f28-7747-4bb3-84dc-ac0a11b0683a">

## Testing notes

Check the story to ensure only one the last breadcrumb is truncated.

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [x] Lint and test workflows pass.

2024-06-28 11:35 UTC, AronPetrauskas requested changes
The original issues to be addressed have been fixed, however while testing I have found some other issues that should probably be addressed here.

2024-06-28 11:35 UTC, AronPetrauskas commented on src/Breadcrumbs/Breadcrumbs.tsx
Now indeed only the last child is truncated. There is another issue however, `itemsAfterCollapse`, `itemsBeforeCollapse` and `maxItems` all seem to do nothing and do not work as described in the docs.

2024-06-28 11:35 UTC, AronPetrauskas commented on src/NumberField/NumberField.tsx
Not sure this is a bug or not, but I can type in a number into this field and then the title of the `NumberField` returns down to a state it is in when `NumberField` is empty. Refer to screenshot.
![image](https://github.com/IPG-Automotive-UK/react-ui/assets/67595415/b6acade6-ef52-4b74-946a-0f6ed7417091)

2024-06-28 11:49 UTC, lukemojo commented on src/Breadcrumbs/Breadcrumbs.tsx
This was a story issue. Args are now being spread correctly and these props should now be function as expected

2024-06-28 12:00 UTC, lukemojo commented on src/NumberField/NumberField.tsx
This is a browser bug in Firefox. MuI seems to deal with it by always collapsing the labels on NumberFields in their examples.  Is this an option @Sowbhagya-ipg? The other way to get around this is by controlling the field and explicitly writing code about what should or shouldn't be allowed in the field. 

If we can collapse the labels I will do that here otherwise this should probably be a separate ticket and PR.

2024-06-28 13:00 UTC, AronPetrauskas approved these changes
`Breadcrumbs` work as expected. I am assuming the `NumberField` issue in Firefox will be addressed later. I am approving the PR.

2024-07-01 06:07 UTC, merged

2024-07-01 06:50 UTC, dmbarry86 commented on src/NumberField/NumberField.tsx
Similar issues already raised https://sce.myjetbrains.com/youtrack/issue/TD-2740/Number-field-doesnt-error-if-non-numeric-value-entered