TD-2862 FileUploader extension validation
IPG-Automotive-UK/react-ui pull request #920
Opened 2024-08-08 10:44 UTC by mattcorner

Contributes to [TD-2862](https://sce.myjetbrains.com/youtrack/issue/TD-2862/Validate-file-extensions-in-the-RUI-Uploader-component)

## Changes

- We no longer render any file rejection messages on hover. This is because the DataTransferItem object we have access to during this event does not contain enough information to correctly validate the file. Instead we wait for the drop event.
- We now validate files based on their extension. react-dropzone internally will allow files that pass the mime-type check through so even if we say `{ acceptedFiles: { "text/plain": [".rd5"] } }`, `.txt` were still being accepted.

## Testing notes

- Check that you do not get any errors on hovering with files. Validation should now only occur on drop.
- Check that for instance the `{ acceptedFiles: { "text/plain": [".rd5"] } }` case no longer allows `.txt` files to be accepted. There is a new automated test to cover this case as well.

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

2024-08-08 20:18 UTC, dmbarry86 commented
As you're here can you please do the feature team a favour and tag on this small update? https://sce.myjetbrains.com/youtrack/issue/TD-2973

2024-08-09 09:00 UTC, mattcorner commented
> As you're here can you please do the feature team a favour and tag on this small update? https://sce.myjetbrains.com/youtrack/issue/TD-2973

I think its a little more complicated than just including it in this PR, but I'll open a separate PR and release them together 👍

2024-08-09 09:40 UTC, arpadlomenipg requested changes
one small change requested

2024-08-09 10:05 UTC, mattcorner commented on src/Uploader/useUploader.ts
> +  const validator = (file: File | DataTransferItem) => {
I linked a react-dropzone bug ticket below this line. The validator does actually run on drag (rightly or wrongly), and in the case of a drag the file is of type DataTransferItem. Typing this correctly here forces us to correctly only handle the drop case in the if statement below.

2024-08-09 10:07 UTC, mattcorner commented on src/Uploader/useUploader.ts
> +  const validator = (file: File | DataTransferItem) => {
In general we shouldn't type things just for our use case, we should type them for how they actually work in practice. Then typescript forces us to handle edge cases correctly.

2024-08-09 10:33 UTC, arpadlomenipg approved these changes
LGTM

2024-08-09 11:04 UTC, arpadlomenipg requested changes
I'm sorry to revert my previous approval, but I noticed meanwhile, that the `FileUploader` and `ImageUploader` is now case sensitive for extensions

2024-08-09 11:04 UTC, arpadlomenipg commented on src/Uploader/useUploader.ts
> +  const acceptedFileExtensions = Object.values(acceptedFiles ?? {}).flat();
please apply a .toLowerCase() to avoid case sensitivity. E.g. right now, ".PNG" is not accepted in the image uploader of FLEET because of this

2024-08-09 11:10 UTC, arpadlomenipg commented on src/Uploader/useUploader.ts
> +    return "." + parts.pop();
please also add a .toLowerCase() here

2024-08-09 13:48 UTC, arpadlomenipg requested changes
the issue is resolved, but I think it might be a good idea to add some unit tests for case sensitivity, in case we change the code again in the future

2024-08-09 13:48 UTC, arpadlomenipg commented on src/FileUploader/FileUploader.test.tsx
>  });
could you please add a unit test for this file, where the `acceptedFiles` is having value ".rd5", but the file name is having ".RD5" extension, so we have a safeguard for case sensitivity in the future if we change something in the code?

Same in the `ImageUploader`, but with value ".png" and ".PNG"

2024-08-09 14:53 UTC, arpadlomenipg approved these changes
LGTM

2024-08-09 15:01 UTC, merged