TD-2804-Cannot-build-CRA-based-apps-with-latest-RUI
IPG-Automotive-UK/react-ui pull request #935
Opened 2024-09-03 14:48 UTC by stevenmcsorleyipg

Commented out 4 recent components that were causing build errors.

Closes TD-2804

## Changes
Fix build errors for CRA-based apps.
This PR addresses the build errors occurring in our CRA based applications when using the latest versions of RUI.
A noted issue was caused by new SVG components added to RUI, specifically the traffic light sign components.

SVG Error Investigation:

While investigating build errors in CRA-based apps, issues with SVG components in RUI were identified:

-- Presence of metadata tags in SVG files.
-- Namespace declarations (xmlns:dc, xmlns:cc, xmlns:rdf, xmlns:svg) not supported by React's JSX.

These elements showed conflicts during the build process. Formatting some of the problematic files allowed the build to progress further but did not fully resolve the issue.

As a temporary solution, we've commented out the exports of the affected SVG components to unblock development and allow updates to the latest RUI version.

## Dependencies
N/A

## UI/UX

The Bug
![image](https://github.com/user-attachments/assets/15fd8fdb-6d52-4a7f-a558-3b947fb2ba95)

The Fix
![image](https://github.com/user-attachments/assets/c9341deb-513d-47c4-be4d-f6287f638188)

## Testing notes

## Author checklist before assigning a reviewer

- [ ] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [ ] PR assigned to me or an appropriate delegate.
- [ ] Relevant labels added to the PR.
- [ ] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

2024-09-03 19:40 UTC, mattcorner requested changes

2024-09-03 19:40 UTC, mattcorner commented on src/index.ts
> +// export { default as VehiclePath, type VehiclePathProps } from "./VehiclePath";
We should also comment out TrafficLight as its part of the same feature set. (Was mentioned in ticket comment)

2024-09-03 19:40 UTC, mattcorner commented on src/index.ts
> +// export { default as VehiclePath, type VehiclePathProps } from "./VehiclePath";
Can we also group the commented exports together at the bottom of the file and leave a comment as to why they are commented out. Leave a link to the bug ticket in YouTrack so can we can trace the detail when we come back and reinstate these in the future.

2024-09-03 19:42 UTC, mattcorner commented
@lukemojo This will need a RUI target release and prerelease for testing. Suggest that it just required a patch release unless there is other RUI work in the pipeline. 

Could you also please take @stevenmcsorleyipg through the RUI PR -> prerelease -> release process that you follow when you get a sec?

2024-09-04 06:06 UTC, lukemojo commented
> @lukemojo This will need a RUI target release and prerelease for testing. Suggest that it just required a patch release unless there is other RUI work in the pipeline.
> 
> Could you also please take @stevenmcsorleyipg through the RUI PR -> prerelease -> release process that you follow when you get a sec?

No problem @mattcorner. I'll create the pre-release branch shortly and we'll go through the release later.

2024-09-04 14:09 UTC, mattcorner approved these changes
lgtm

2024-09-04 14:24 UTC, merged