TD-3034 Road Preview Component
IPG-Automotive-UK/react-ui pull request #943
Opened 2024-09-09 12:22 UTC by jzhelyazkovtvm

Closes [TD-3034](https://sce.myjetbrains.com/youtrack/issue/TD-3034/Add-new-RoadPreview-component-to-RUI)
Contributes to [TD-2983](https://sce.myjetbrains.com/youtrack/issue/TD-2983/Road-Hover-Preview)

## Changes

Created RoadPreview directory with RoadPreview stories file, test file, types file, index file.
The component is imported in main index.ts file.
Created mock data for rendering the component in storybook in RoadPreview.stories.
Created unit tests for the component in RoadPreview test file.
The current component uses another components for visualizing data, which are: UserAvatar, NoWrapTypography, TruncatedTooltip, VersionChip and LabelChipGroup.
2 Icons are imported in /static folder, for CarMaker logo and ASAM OpenSCENARIO.
The props createdAt, user and label are optional. All others are required

A brief description of what this pull request solves / introduces.

- New component named RoadPreview, which has to replace the current in 4 different places.

## Dependencies

N/A

## UI/UX

![image](https://github.com/user-attachments/assets/4b847164-cf7c-4e96-bec2-597b80db7ec2)

## Testing notes

We can view 3 testing scenarios in storybook from Figma prototype

## Author checklist before assigning a reviewer

- [x] Reviewed my own code-diff.
- [x] Branch has been run in docker.
- [x] PR assigned to me or an appropriate delegate.
- [x] Relevant labels added to the PR.
- [x] Appropriate tests have been added.
- [x] Lint and test workflows pass.

2024-09-09 12:32 UTC, m4manjesh commented
@jzhelyazkovtvm Please fix the conflicts. I think this should be merging to a staging branch instead of main, please check with @lukemojo

2024-09-09 15:01 UTC, m4manjesh requested changes
Component looks good, some suggestions to improve the code. Next time please try to attach Figma if available. Also this PR has some changes of `DialogTitle` , may be because you created this branch from Main and i think this PRs base branch dont have those changes?

2024-09-09 15:10 UTC, dmbarry86 commented on src/RoadPreview/RoadPreview.tsx
> +  function getCurrentDateFormatted() {
I agree. I think each app should already be formatting the timstamps, for which we use a library.

2024-09-10 06:14 UTC, jzhelyazkovtvm commented
> Component looks good, some suggestions to improve the code. Next time please try to attach Figma if available. Also this PR has some changes of `DialogTitle` , may be because you created this branch from Main and i think this PRs base branch dont have those changes?

After pushing changes I had conflicts and also the branch was created before the release from main branch. So then the base branch was changed to v8.0.0 which was the final release and I believe this is the reason I have changes on this branch.

2024-09-10 06:29 UTC, jzhelyazkovtvm commented on src/RoadPreview/RoadPreview.tsx
> +  key: React.Key
Removed

2024-09-10 09:08 UTC, m4manjesh requested changes
Please make the changes in the stories and add tests as discussed.

2024-09-10 10:41 UTC, m4manjesh requested changes
Sorry i missed this my initial review. Please make the changes for default exports then we are good to go.

2024-09-10 10:41 UTC, m4manjesh commented on src/RoadPreview/RoadPreview.tsx
> +export default function RoadPreview({
we should change to using named exports as per the new style guide that we use in VIRTO.
https://github.com/IPG-Automotive-UK/virto/blob/qa/STYLEGUIDE.md#exports

```suggestion
export function RoadPreview({
```

2024-09-10 10:41 UTC, m4manjesh commented on src/index.ts
> +export { default as RoadPreview, type RoadPreviewProps } from "./RoadPreview";
```suggestion
export { RoadPreview, type RoadPreviewProps } from "./RoadPreview";
```

2024-09-10 10:41 UTC, m4manjesh commented on src/RoadPreview/index.ts
> +export { default } from "./RoadPreview";
```suggestion
export { RoadPreview } from "./RoadPreview";
```

2024-09-10 10:41 UTC, m4manjesh commented on src/RoadPreview/RoadPreview.stories.tsx
> +import RoadPreview from "./RoadPreview";
```suggestion
import { RoadPreview } from "./RoadPreview";
```

2024-09-10 10:41 UTC, m4manjesh commented on src/RoadPreview/RoadPreview.test.tsx
> +import RoadPreview from ".";
```suggestion
import { RoadPreview } from ".";
```

2024-09-10 12:06 UTC, m4manjesh approved these changes
LGTM

2024-09-10 12:13 UTC, merged