VE-141 - Re-implement NumberField
IPG-Automotive-UK/react-ui pull request #959
Opened 2024-09-26 15:50 UTC by lukemojo

Contributes [TD-141](https://sce.myjetbrains.com/youtrack/issue/VE-141/Re-implement-string-conversion-to-number-in-NumberField)

## Changes

Reinstates all the previous functionality of NumberField along with the string to number conversion. Now returns a value rather than an event. This is a breaking change requiring updates in the VIRTO and CRA apps.

There is a sneaky one liner in here fixing the colour of the ConfirmDialog text in dark mode.

A brief description of what this pull request solves / introduces.

- This effectively reverts the change to using a standard MUI Input to performing number conversion
- The output has changed because this is now a TS component so we no longer try and hijack the event 
- These changes prevent the need for converting to a number in applications (but will still require string coercion in Zod session schemas)
- Reinstating the old functionality should allow instrument designer updates with minimum updates
- Fixes dark mode confirmation text

## Testing notes

- NumberField stories should now show a value onChange rather than the event
- Text should be white in dark mode ConfirmDialog

## Author checklist

Before I request a review:

- [x] I have reviewed my own code-diff.
- [x] I have tested a pre-release
- [x] I have assigned the PR to myself or an appropriate delegate.
- [x] I have added the relevant labels to the PR.
- [x] I have included appropriate tests.
- [x] I have checked that the Lint and Test workflows pass on Github.
- ~~[ ] I have populated the deploy-preview with relevant test data.~~

2024-09-27 08:09 UTC, mattcorner commented
Shouldn't RUI PRs have a target release? This is currently destined for main.

2024-09-27 08:16 UTC, mattcorner requested changes
Discussed to undo the breaking change to the onChange interface and correctly type it. Applications can use `NumberFieldProps["onChange"]` to get the correct types for the callback method.

We should be much more considerate about making breaking changes in components like this that are widely used not just in one or two VIRTO apps, but across the whole suite as well as in other tools.

2024-10-01 14:23 UTC, mattcorner requested changes

2024-10-01 14:23 UTC, mattcorner commented on src/NumberField/NumberField.test.tsx
> +  onChange?: (value: number) => void;
Is this correct? onChange takes an event. Why do we even need to override the type for this?

2024-10-01 14:23 UTC, mattcorner commented on src/NumberField/NumberField.tsx
> + * @returns {number} - The converted value.
Don't add types to jsdoc
```suggestion
 * @param value - The value to convert.
 * @returns - The converted value (either a number of null)
```

2024-10-01 14:23 UTC, mattcorner commented on src/NumberField/NumberField.tsx
> + * @returns {number} - The converted value.
Same point applies to all of these utility methods.

2024-10-01 14:23 UTC, mattcorner commented on src/NumberField/NumberField.stories.tsx
> +  const onChange = (event: NumberFieldChangeEvent) => {
As a result I'd prefer not to export NumberFieldChangeEvent from RUI. This is consistent with MUI.

2024-10-01 14:23 UTC, mattcorner commented on src/NumberField/NumberField.stories.tsx
> +    max: 1,
You've set the initial value on this story to something that shows an error message other than the one passed in. Suggest that you set the initial value to something valid / don't include a min/,ax for this story.

2024-10-01 14:23 UTC, mattcorner commented on src/NumberField/NumberField.types.ts
> +  min?: number;
Missing jsdoc for these props

2024-10-01 14:23 UTC, mattcorner commented on src/NumberField/NumberField.stories.tsx
Only some of the stories here are showing the onBlur action. I thought this should come for free so a bit confused why we handle it manually in some and not for others.

2024-10-03 14:18 UTC, dmbarry86 commented
> Shouldn't RUI PRs have a target release? This is currently destined for main.

@lukemojo we've had to do v8.10.0 release whilsy you were not working today so you will need to target another release number now for this PR. Still it is targetted to main also. I'll leave you to create the next release branch.

2024-10-16 10:00 UTC, mattcorner requested changes
Is there a corresponding VIRTO branch where we have proven that the pre-release for this fixes [TD-3085](https://sce.myjetbrains.com/youtrack/issue/TD-3085/Error-publishing-a-sensor) and also integrates into the wizards e.g. SCENE?

2024-10-16 10:01 UTC, mattcorner commented on src/NumberField/NumberField.test.tsx
> +  onChange?: (value: number) => void;
Hasn't been addressed.

2024-10-17 18:51 UTC, lukemojo commented
> Is there a corresponding VIRTO branch where we have proven that the pre-release for this fixes [TD-3085](https://sce.myjetbrains.com/youtrack/issue/TD-3085/Error-publishing-a-sensor) and also integrates into the wizards e.g. SCENE?

There is a PR for this in VIRTO that I haven't yet linked as it's on the pre-release. 
https://github.com/IPG-Automotive-UK/virto/pull/1094

If we're happy with how the deploy-preview is functioning then I will release this and update in the VIRTO PR

2024-10-18 10:12 UTC, mattcorner approved these changes
LGTM. Tested in https://github.com/IPG-Automotive-UK/virto/pull/1094 and works well. Go ahead and release and integrate into that PR.

2024-10-18 10:20 UTC, merged