TD 3111 Add Status Count Bar Component
IPG-Automotive-UK/react-ui pull request #962
Opened 2024-10-01 15:04 UTC by jzhelyazkovtvm

Contributes [TD-3111](https://sce.myjetbrains.com/youtrack/issue/TD-3111/Display-StatusCountBar-in-TestTable)

## Changes

Changed Props of the StatusCountBar component, for the count object which currently is Record<Status, number>. This change is necessary, because there is an error currently in Virto Test. This error is caused by differences in types for status in ipguk/types and Status types in RUI. In RUI there are many types supported and listed below:
type Status = "aborted" | "completed" | "disrupted" | "errored" | "failed" | "no-metrics" | "not-ready" | "not-run" | "operational" | "passed" | "pending" | "queued" | "ready" | "running"
In ipguk/types there are the following status types: 
type Status = "aborted" | "completed" | "errored" | "not-ready" | "queued" | "ready" | "running";
This is a mismatch and that's why I have updated the StatusCountBar component props instead of Status type in the record, to Partial<Status>.

A brief description of what this pull request solves / introduces.

- Fixed type mismatch between the Test app types and RUI types.

Maybe a short description of what is not included and will come in future work where appropriate.

## Dependencies

N/A

## UI/UX

N/A

## Testing notes

N/A

## Author checklist

Before I request a review:

- [x] I have reviewed my own code-diff.
- ~[ ] I have tested the changes in Docker / a deploy-preview.~
- [x] I have assigned the PR to myself or an appropriate delegate.
- [x] I have added the relevant labels to the PR.
- ~[ ] I have included appropriate tests.~
- [x] I have checked that the Lint and Test workflows pass on Github.
- ~[ ] I have populated the deploy-preview with relevant test data.~

2024-10-01 15:41 UTC, m4manjesh requested changes
I think you need to do the same for `src\Status\StatusCountTable\StatusCountTable.types.ts` as this is a seperate component

2024-10-02 05:45 UTC, dmbarry86 commented
Looks to me like StatusCountBarProps and StatusCountTableProps are identical. Don't duplicate code. Just make one of them the master and the other one can simply reuse that type and rexport it as it's own.

2024-10-02 05:56 UTC, dmbarry86 commented on src/Status/StatusCountBar/StatusCountBar.types.ts
> +  count: Record<Partial<Status>, number>;
I think you have this type wrong and haven't fixed the issue. Partial around status means nothing here. You need partial around record I think.

See example https://www.typescriptlang.org/play/?#code/C4TwDgpgBAysCGwCuBnKBeKAiA5gezwBMsoAfbAI3mLOyRwBsQsAoF0SKAYTyQDtgGKAAV4AJ2ABLeAwA8AJQgBjPGMKy4iVABoofJAFsKEMQD5TbDtADqYvHxxDFKtbNETpczchSnd+oxMLNhU+FEEVfmAALm5eASEAb1wCYliAZgBfAG4WUPCoAHc7B1jbe0dMZKo0qAAWHKA

2024-10-02 05:58 UTC, dmbarry86 requested changes
* Remove duoplication
* Actually fix the bug

2024-10-02 06:58 UTC, dmbarry86 commented
I think you missed the point about the duplication. The whole type is duplicated, both title and count, not just count. Easier if I just fix it I think.

2024-10-02 07:04 UTC, jzhelyazkovtvm commented
> I think you missed the point about the duplication. The whole type is duplicated, both title and count, not just count. Easier if I just fix it I think.

I thought you are talking about the StatusCount, but now I see you meant the whole props type

2024-10-02 07:11 UTC, dmbarry86 commented
> I was thinking we can reuse this StatusCount type if needed somewhere else.

If you did need to do that (which we don't yet) you can just extract it. Don't need to export it per se.

```
import type {StatusCountTableProps} from "./StatusCountTable.types"

type StatusCount = StatusCountTableProps["count"];
```

2024-10-02 08:10 UTC, m4manjesh approved these changes
LGTM

2024-10-02 08:11 UTC, merged