enhancement/TD-3161 Model Button Edit Styles
IPG-Automotive-UK/react-ui pull request #974
Opened 2024-11-05 08:56 UTC by jzhelyazkovtvm

Closes [TD-3161](https://sce.myjetbrains.com/youtrack/issue/TD-3161/Edit-the-styles-of-ModelButton-in-React-UI)

## Changes

Updated ModelButton to show status icon on top right of the button. Borders and background color also updated to match the status colors defined in figma, with new hover behaviour as well. Popup button also has now outlined style, matching the colors for the statuses and background as well.

A brief description of what this pull request solves / introduces.

- Updated ModelButton with status icon and background + borders
- Old styles for when button is disabled or no children are still the same

## Dependencies

N/A

## UI/UX
Before
![image](https://github.com/user-attachments/assets/94760a63-8718-4576-9c45-d220d4d6f7f8)

After
![image](https://github.com/user-attachments/assets/9910c5c0-e5a1-46b4-95ce-5c6f52b83d74)
![image](https://github.com/user-attachments/assets/72c2164c-e792-42ae-b2ba-0e80502dea0e)
![image](https://github.com/user-attachments/assets/2924e61f-288f-4f2d-bfd0-a65e12a84bfb)
![image](https://github.com/user-attachments/assets/108f4e55-0951-4b83-b94d-2157ff012e4d)

[Figma prototype](https://www.figma.com/design/aFUbF9gTc2OfeLQnSf6BAF/VIRTO.BUILD?node-id=7574-26411&node-type=frame&t=DNhpHoaLpbedAS3p-0)

## Testing notes

N/A

## Author checklist

Before I request a review:

- [x] I have reviewed my own code-diff.
- ~[ ] I have tested the changes in Docker / a deploy-preview.~
- [x] I have assigned the PR to myself or an appropriate delegate.
- [x] I have added the relevant labels to the PR.
- [x] I have included appropriate tests.
- [x] I have checked that the Lint and Test workflows pass on Github.
- ~[ ] I have populated the deploy-preview with relevant test data.~
- ~[ ] I have tagged a UI/UX designer for review if this PR includes UI/UX changes.~

2024-11-06 11:28 UTC, m4manjesh requested changes
@jzhelyazkovtvm  this PR inlcudes non related changed to this PR, please fix it. Also please update the testing notes.

2024-11-06 12:47 UTC, jzhelyazkovtvm commented
> @jzhelyazkovtvm this PR inlcudes non related changes, please fix it. Please update the testing notes with what needed to be tested, Author checklists are not checked correclty, this PR still created a deply-preview, if you tested it there the second point should be checked. I see that @Sowbhagya-ipg approved the UI in another PR, but i suggest in future tag her here as well so can fix any UI issue upfront

We agreed on Tagging UX designer for VIRTO Model and Fleet, where the buttons are rendered with pre-release of RUI.

2024-11-06 13:36 UTC, m4manjesh commented
> > @jzhelyazkovtvm this PR inlcudes non related changes, please fix it. Please update the testing notes with what needed to be tested, Author checklists are not checked correclty, this PR still created a deply-preview, if you tested it there the second point should be checked. I see that @Sowbhagya-ipg approved the UI in another PR, but i suggest in future tag her here as well so can fix any UI issue upfront
> 
> We agreed on Tagging UX designer for VIRTO Model and Fleet, where the buttons are rendered with pre-release of RUI.

Make sure you share the testing PR link here, ok in this case as i'm reviewing the other one.

2024-11-06 14:41 UTC, m4manjesh requested changes
not directly realted but i see we are using `PaperProps` for the popover which is depricated, please use the following instead `slotProps={{ paper: { sx: { borderRadius: 2, padding: 2 } } }}`

Component looks good, some small suggestions

2024-11-06 14:41 UTC, m4manjesh commented on src/ModelButton/ModelButton.tsx
> +  status: string,
props types should live in `ModelButton.types.ts`

2024-11-06 14:43 UTC, m4manjesh commented on src/ModelButton/ModelButton.test.tsx
> +    render(<ModelButton status="error" />);
Test below already doing the same. You can test no icon renderes if the status is `non`

2024-11-06 14:44 UTC, m4manjesh commented on src/ModelButton/ModelButton.test.tsx
> +  test("does apply background color", () => {
Test above is going the same, instead you can test case `none`

2024-11-07 06:41 UTC, jzhelyazkovtvm commented
> > > @jzhelyazkovtvm this PR inlcudes non related changes, please fix it. Please update the testing notes with what needed to be tested, Author checklists are not checked correclty, this PR still created a deply-preview, if you tested it there the second point should be checked. I see that @Sowbhagya-ipg approved the UI in another PR, but i suggest in future tag her here as well so can fix any UI issue upfront
> > 
> > 
> > We agreed on Tagging UX designer for VIRTO Model and Fleet, where the buttons are rendered with pre-release of RUI.
> 
> Make sure you share the testing PR link here, ok in this case as i'm reviewing the other one.

![image](https://github.com/user-attachments/assets/711b3bf0-b0c2-4822-ac7a-86d2db90634d)

2024-11-07 11:15 UTC, jzhelyazkovtvm commented
@m4manjesh  we will not need pre-release this time, since there are no changes in the UI

2024-11-07 12:21 UTC, m4manjesh approved these changes
LGTM

2024-11-07 12:24 UTC, merged