VE-221 Migrate deprecated APIs
IPG-Automotive-UK/react-ui pull request #989
Opened 2024-11-27 11:43 UTC by m4manjesh

Closes [VE-221](https://sce.myjetbrains.com/youtrack/issue/VE-221/Migrating-from-deprecated-APIs)

## Changes

During the RUI migration to MUI v6 [here](https://github.com/IPG-Automotive-UK/react-ui/pull/984), we noticed it is good to handle deprecations now before they become breaking changes. This PR focuses on migrating recently deprecated APIs to stay up-to-date and improve the developer experience.

A brief description of what this pull request solves / introduces.

- Many system props such as `mt`, `bgColor` and more are deprecated in Box, Typography, Link, Grid, and Stack components. So here we are moving the most of the of the system props to `sx` props. See below example
![Screenshot 2024-11-27 122048](https://github.com/user-attachments/assets/b3284cee-5d03-4fff-8fd4-65335a3ddd76)

- `Hidden` component was already deprecated. Remove it and use `useMediaQuery` to achieve the same behaviour as follows
![Screenshot 2024-11-27 122202](https://github.com/user-attachments/assets/fe99d0c1-5bb9-41d4-bbf5-42e53ddc594b)

- In [ThemeProvider.tsx](https://github.com/IPG-Automotive-UK/react-ui/pull/989/files#diff-9f7f950eeb101f410b8e0af8bae8386a88a565945932b0fb1ae41875c5ff1d95) i have added `mixins.toolbar.minHeight to 64` to fix `AppLauncherover` overlapping issue with `AppHeader` in VIRTO apps. Also changed using custom `64px` in `VirtoAppLayout` and `AppLayout` to calculate `height` and `top`, instead of using `theme.mixins.toolbar.minHeight`.

Before
![Screenshot 2024-11-27 123832](https://github.com/user-attachments/assets/da6ee9b1-b886-4899-8298-cd7bf6623437)

After
![Screenshot 2024-11-27 123839](https://github.com/user-attachments/assets/0af75e38-890f-41d3-945a-9dcc35394574)

- All the analogous APIs such as `components` and `componentProps`  are deprecated and eventually removed. Using  standardized `slots` and `slotProps` instead
![Screenshot 2024-11-27 124200](https://github.com/user-attachments/assets/3e20fb6d-3d2f-4643-8fd4-301ff536627b)
![Screenshot 2024-11-27 124654](https://github.com/user-attachments/assets/4e0f9f5e-93fc-48d6-aa17-9a350c2aa21b)

## Dependencies

This needs to wait to merge until this [PR ](https://github.com/IPG-Automotive-UK/react-ui/pull/984) gets merged

## UI/UX

There are some small UI changes related to `AppLauncher` top spacing as mentioned above. It would be good to get reviewed by you @Sowbhagya-ipg.

## Testing notes

Most of the components touched and most of the changes are identical in this PR. But still, make sure all stories are still working the same as before. Check that the changes i made in `VirtoAppLayout` and `AppLayout` didn't break the behaviour we have.

## Author checklist

Before I request a review:

- [x] I have reviewed my own code-diff.
- [x] I have tested the changes in Docker / a deploy-preview.
- [x] I have assigned the PR to myself or an appropriate delegate.
- [x] I have added the relevant labels to the PR.
- [ ] ~I have included appropriate tests.~
- [x] I have checked that the Lint and Test workflows pass on Github.
- [ ] ~I have populated the deploy-preview with relevant test data.~
- [x] I have tagged a UI/UX designer for review if this PR includes UI/UX changes.

2024-11-27 15:48 UTC, Sowbhagya-ipg commented
The app layout changes looks good @m4manjesh

2024-12-05 17:59 UTC, nikitharani commented
![image](https://github.com/user-attachments/assets/ee8cbd6c-92e7-4a57-ae04-c8f47244663a)
Sidebar item title not visible in darkmode

2024-12-08 21:47 UTC, nikitharani requested changes
The changes are mostly good, with only a few minor adjustments needed.

2024-12-09 09:19 UTC, mattcorner commented on src/PasswordChangeDialog/PasswordChangeDialog.jsx
> +            <Alert severity="success" sx={{ marginBottom: 1 }}>
In the MUI spacing convention 1 unit is 8px, so the correct replacement would be `sx={{ mb: 2 }}`

2024-12-09 10:13 UTC, mattcorner reviewed
Looks good to me. Tested the AppLayout changes and works well. Reran the mui deprecation codemod and picked up no other changes. Just Nikithas feedback to address.

2024-12-10 10:24 UTC, m4manjesh commented
> ![image](https://private-user-images.githubusercontent.com/49191249/392936201-ee8cbd6c-92e7-4a57-ae04-c8f47244663a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjMyMjUsIm5iZiI6MTczMzgyMjkyNSwicGF0aCI6Ii80OTE5MTI0OS8zOTI5MzYyMDEtZWU4Y2JkNmMtOTJlNy00YTU3LWFlMDQtYzhmNDcyNDQ2NjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA5Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTdlNTQ2YmQxMjA3OTUxYTU3ODEwYTNhM2UzOTFmMjMwZDUyYTIzNjIyMGYzNDljYWJhMjI4ZGUxMzk5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H1VFGWhabmCUJ4kYs8MDtbxxnSriVvFz-SyaEh6-OHg) ![image](https://private-user-images.githubusercontent.com/49191249/392936775-a36d703c-0325-401a-ba1e-4f415a01b38c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjMyMjUsIm5iZiI6MTczMzgyMjkyNSwicGF0aCI6Ii80OTE5MTI0OS8zOTI5MzY3NzUtYTM2ZDcwM2MtMDMyNS00MDFhLWJhMWUtNGY0MTVhMDFiMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA5Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Y2RkZDA5ODJmMmE5NWQ1ZmUzZGFhZGQ3NzdjYzJjYzgwYzRlY2U2N2FhODJhMTU1OGU0OTBiMzFhMjUwNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6vN-MzRDoSleTTLv88wTuh0QVheGC837S7DxblGIcxU)
> 
> Sidebar item text not visible in darkmode

Good catch. Seems like this is working fine with `VirtoAppLayout`. But still this is an issue in this PR, we have similar kind of issues with storybook mode switching in few places, this will be addressed with a PR coming for  [VE-252](https://sce.myjetbrains.com/youtrack/issue/VE-252/Combine-dark-and-light-theme-for-MUI-v6)

2024-12-10 15:15 UTC, nikitharani requested changes
Please change mb in passwordChangeDialog otherwise everything lgtm.

2024-12-10 17:07 UTC, merged